# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# The contents of this file or a pointer to this file should
# be set to the ENV variable:
#
# KADR_DNS_PROVIDER_CONFIG_YAML=[yaml | file@/path/reference]
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

#---------------------------------------------------------------------------
# Configuration for supported dnsproviders:
# https://github.com/bitsofinfo/kubernetes-acme-dns-registrar/tree/main/core/dnsprovider
#
# dnsproviders are responsible for managing the CNAME records for the 
# acme-dns challenge server for each fqdn in a zone that is detected
# by the underlying watcher and subsequent acme-dns registration
#
# the contents of this file is merged with dns-provider-secrets.yaml
#---------------------------------------------------------------------------

dns_providers:

  #--------------------------
  # example for CLOUDFLARE
  #--------------------------
  cloudflare:

    # provider is enabled or not?
    enabled: true

    # common settings, can be overriden per zone below
    zone_id: 9d518b982eb37d6f1f5d1534e9ff989a

    zones:

      # zones that we will manage CNAME records in
      my-domain.net:
        zone_name: irembo-test.org
        ttl: 300

        # only manage dns CNAMEs for 
        # AcmeDnsRegistationEvent.Registration.cname_name 
        # that matches the following patterns (ANY match)
        includes: 
          - ".+\\.irembo-test\\.org"

        # ignore/exclude dns CNAMEs management for 
        # AcmeDnsRegistationEvent.Registration.cname_name
        # that matches the following patterns (ANY match)
        excludes: null

        # optional can override the top level settings here per zone
        #zone_id: yyy

  #--------------------------
  # example for AZUREDNS
  #--------------------------
  azuredns:

    # provider is enabled or not?
    enabled: false

    # common settings, can be overriden per zone below
    subscription_id: xxx
    tenant_id: yyy
    client_id: zzz

    zones:

      # zones that we will manage CNAME records in
      my-domain.net:
        resource_group_name: some-rg
        zone_name: my-domain.net
        ttl: 300

        # only manage dns CNAMEs for 
        # AcmeDnsRegistationEvent.Registration.cname_name 
        # that matches the following patterns (ANY match)
        includes: 
          - ".+\\.my-domain\\.net"

        # ignore/exclude dns CNAMEs management for 
        # AcmeDnsRegistationEvent.Registration.cname_name
        # that matches the following patterns (ANY match)
        excludes: null

        # optional can override the top level settings here per zone
        #subscription_id: xxx
        #tenant_id: yyy
        #client_id: zzz

