# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# The contents of this file or a pointer to this file should
# be set to the ENV variable:
#
# KADR_K8S_WATCHER_CONFIG_YAML=[yaml | file@/path/reference]
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

#---------------------------------------------------------------------------
# Configures the underlying k8swatcher for what k8s events it will
# watch and create DomainNameEvents for that will lead acme-dns registrations
#
# @see https://github.com/bitsofinfo/k8swatcher
#---------------------------------------------------------------------------

k8s_watch_configs:
  - id: all_ingress_my-apps
    namespace: my-apps
    kind: Ingress
    sdk_client_class_name: NetworkingV1Api
    sdk_list_function_name: list_ingress_for_all_namespaces
    field_selector: null
    label_selector: null
    suppress_bookmarks: true
    include_k8s_objects: true
