
{{- if hasKey .Values.rbac "enabled" }}
  {{ if eq .Values.rbac.enabled true }}

{{- $_ := set . "stdlabelsargs" (dict "root" $) }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.rbac.serviceAccountName }}
  namespace: {{ .Values.rbac.serviceAccountNamespace }}
  labels:
    {{ include "kadr.stdlabels" $.stdlabelsargs | indent 4 }}

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.rbac.k8swatcherClusterRoleName }}
  labels:
    {{ include "kadr.stdlabels" $.stdlabelsargs | indent 4 }}
rules:
  - apiGroups:
      - "networking.k8s.io"
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch


---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.rbac.acmeDnsJsonRoleName }}
  namespace: {{.Values.rbac.acmeDnsJsonSecretNamespace }}
  labels:
    {{ include "kadr.stdlabels" $.stdlabelsargs | indent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    resourceNames:
      -  {{ .Values.rbac.acmeDnsJsonSecretName }}
    verbs:
      - get
      - list
      - patch


---

# ClusterRoleBinding 
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.rbac.k8swatcherClusterRoleBindingName }}
  labels:
    {{ include "kadr.stdlabels" $.stdlabelsargs | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.rbac.k8swatcherClusterRoleName }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.rbac.serviceAccountName }}
  namespace: {{ .Values.rbac.serviceAccountNamespace }}
---


# RoleBinding 
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.rbac.acmeDnsJsonRoleBindingName }}
  namespace: {{.Values.rbac.acmeDnsJsonSecretNamespace }}
  labels:
    {{ include "kadr.stdlabels" $.stdlabelsargs | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.rbac.acmeDnsJsonRoleName }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.rbac.serviceAccountName }}
  namespace: {{ .Values.rbac.serviceAccountNamespace }}
---

  {{ end }}
{{ end }}