
{{- if hasKey .Values.rbac "enabled" }}
  {{ if eq .Values.rbac.enabled true }}

{{- $_ := set . "stdlabelsargs" (dict "root" $) }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.rbac.serviceAccountName }}
  namespace: {{ .Values.rbac.serviceAccountNamespace }}
  labels:
    {{ include "kadr.stdlabels" $.stdlabelsargs | indent 4 }}

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.rbac.clusterRoleName }}
  labels:
    {{ include "kadr.stdlabels" $.stdlabelsargs | indent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    resourceNames:
      -  {{ .Values.rbac.acmeDnsJsonSecretNamespace }}/{{ .Values.rbac.acmeDnsJsonSecretName }}
    verbs:
      - get
      - list
      - patch

  - apiGroups:
      - "networking.k8s.io"
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch

---

# ClusterRoleBinding | RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.rbac.clusterRoleBindingName }}
  labels:
    {{ include "kadr.stdlabels" $.stdlabelsargs | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.rbac.serviceAccountName }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.rbac.serviceAccountName }}
  namespace: {{ .Values.rbac.serviceAccountNamespace }}
---


  {{ end }}
{{ end }}