apiVersion: v1
entries:
  kubernetes-acme-dns-registrar:
  - apiVersion: v1
    appVersion: 0.0.1
    created: "2022-05-18T12:21:58.223219-06:00"
    description: Chart for installing kubernetes-acme-dns-registrar
    digest: 97bb26ea01d484de0e03fe0c1d8504e0dffa46c3c24efb666ab6bd16a8f7e14d
    name: kubernetes-acme-dns-registrar
    urls:
    - charts/kubernetes-acme-dns-registrar-0.0.1.tgz
    version: 0.0.1
generated: "2022-05-18T12:21:58.222308-06:00"
