name: Build, test, publish
on: push

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Dev set version number
        if: startsWith(github.ref, 'refs/tags') == false
        run: |
          pwd
          ls -al 
          pip install --upgrade dunamai
          export VERSION_NUMBER=$(dunamai from git --format dev-0.0.0.{timestamp})
          echo "VERSION_NUMBER: $VERSION_NUMBER"
          echo "VERSION_NUMBER=$VERSION_NUMBER" >> $GITHUB_ENV
      
      - name: Dev Build and push
        if: startsWith(github.ref, 'refs/tags') == false
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/kubernetes-acme-dns-registrar:${{ env.VERSION_NUMBER }},${{ secrets.DOCKERHUB_USERNAME }}/kubernetes-acme-dns-registrar:latest-dev
